### ISSUE TITLE
Setting up The Kanban Board

### ISSUE THREAD

**Issue by Chaseknis** [Chaseknis/second_capstone_Js#21]
## Done so far ✔️ 
- Create an empty Repository ☑️  
- Copy the GitHub project Board ☑️ 
- Open the GitHub project (Kanban board) in your team repo ☑️  
- Assign a Task to each group member ☑️ 
- Remove All cards with `Student C` in the title ☑️ 

_Our Team consists of two people_

**Comment by huseyinbiyik** [comment]
Hi @LDouglasOT and @Chaseknis 

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Issue description is great 💯 
- All cards are assigned 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chaseknis** [comment]
@huseyinbiyik Thank you!
